# Generated by Django 3.2.15 on 2022-11-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quote',
            field=models.TextField(null=True),
        ),
    ]
