# Generated by Django 3.2.16 on 2022-11-24 04:52

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_article_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='quote',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
