version: '3'

services:
  web:
    restart: always
    build: ./
    expose:
      - "8666"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./:/usr/src/app/
    env_file: .env
    command: gunicorn DarkMatterMaytok.wsgi:application --workers 9 --bind 0.0.0.0:8666
    entrypoint: ["sh", "/usr/src/app/entrypoint.sh"]

  minio:
    image: minio/minio:RELEASE.2020-10-18T21-54-12Z
    volumes:
      - maytok_minio:/data
    expose:
      - "9000"
    env_file: .env

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - maytok_postgres:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - maytok_redis:/data

volumes:
  maytok_minio:
  maytok_postgres:
  maytok_redis:
