version: '3.8'

services:
  web:
    restart: always
    build: ./
    #image: darkmattermaytok:latest
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn DarkMatterMaytok.wsgi:application -w 2 -b :8000
    entrypoint: ["sh", "/entrypoint.sh"]

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata:
