# Generated by Django 3.0.5 on 2020-05-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('X', 'COURTIER'), ('B', 'BARON'), ('C', 'COUNT'), ('D', 'DUKE'), ('K', 'KING'), ('E', 'EMPEROR')], default='X', max_length=50),
        ),
    ]
