# Generated by Django 3.2.12 on 2022-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_founder_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
