# Generated by Django 3.2.12 on 2022-04-11 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220406_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='founder_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
