# Generated by Django 3.2.12 on 2022-04-11 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_founder_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='founder_uuid',
        ),
        migrations.AddField(
            model_name='user',
            name='guid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
