# Generated by Django 3.0.5 on 2020-04-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
