# Generated by Django 3.0.5 on 2020-05-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200426_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='game_icon',
            field=models.ImageField(blank=True, null=True, upload_to='game_icons/'),
        ),
    ]
