# Generated by Django 3.0.5 on 2020-05-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_chapter_game_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
