# Generated by Django 3.0.5 on 2020-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_backgrounds/'),
        ),
    ]
