# Generated by Django 3.0.5 on 2020-05-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_chapter_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='number',
            new_name='chapter_number',
        ),
    ]
