# Generated by Django 3.0.5 on 2020-05-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200504_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
