# Generated by Django 3.1.1 on 2020-09-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_chapter_sounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='sounds',
            field=models.JSONField(default=dict),
        ),
    ]
