# Generated by Django 3.1.4 on 2021-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20210115_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='big_cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_big_covers/'),
        ),
    ]
