# Generated by Django 3.0.5 on 2020-04-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200410_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
