# Generated by Django 3.0.5 on 2020-04-24 02:52

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
