# Generated by Django 3.2.12 on 2022-04-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
    ]
