# Generated by Django 3.2.12 on 2022-04-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_is_founder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_founder',
            new_name='is_founder_only',
        ),
    ]
