# Generated by Django 3.2.12 on 2022-04-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_is_founder_post_is_founder_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_founder_only',
        ),
    ]
