# Generated by Django 3.1.1 on 2020-09-23 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_debts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debts',
            new_name='Debt',
        ),
    ]
